/**
 * Emits supabase/migrations/0002_seed.sql from src/content/site.ts, so the
 * database starts with exactly what the site shows today. Re-run it any
 * time the static content changes and you want a fresh seed.
 *
 *   node scripts/gen-seed.mjs
 */
import { writeFileSync } from "node:fs";
import { site } from "../src/content/site.ts";

const q = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const arr = (a) => `ARRAY[${a.map(q).join(", ")}]::text[]`;
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;

const L = [];
L.push("-- ===================================================================");
L.push("-- Standard Solar — seed");
L.push("-- Generated by scripts/gen-seed.mjs from src/content/site.ts.");
L.push("-- Safe to re-run: every insert upserts on its primary key.");
L.push("-- ===================================================================");
L.push("");

// --- settings -------------------------------------------------------
const settings = {
  hero: {
    eyebrow: site.hero.eyebrow,
    headline: site.hero.headline,
    subhead: site.hero.subhead,
    mobileImage: site.hero.mobileImage,
    mobileImageAlt: site.hero.mobileImageAlt,
    desktopImage: site.hero.desktopImage,
    desktopImageAlt: site.hero.desktopImageAlt,
  },
  stats: site.stats,
  ctaBand: site.ctaBand,
  company: site.company,
};
L.push("insert into public.site_settings (key, value) values");
L.push(
  Object.entries(settings)
    .map(([k, v]) => `  (${q(k)}, ${json(v)})`)
    .join(",\n") + "\non conflict (key) do update set value = excluded.value;",
);
L.push("");

// --- sectors --------------------------------------------------------
L.push("insert into public.sectors (id, position, title, kicker, description, overview, applications, figures, image_url) values");
L.push(
  site.sectors.items
    .map(
      (s, i) =>
        `  (${q(s.id)}, ${i}, ${q(s.title)}, ${q(s.kicker)}, ${q(s.description)}, ${q(s.overview)}, ${arr(s.applications)}, ${json(s.figures)}, ${q(s.image)})`,
    )
    .join(",\n") +
    "\non conflict (id) do update set position = excluded.position, title = excluded.title," +
    " kicker = excluded.kicker, description = excluded.description, overview = excluded.overview," +
    " applications = excluded.applications, figures = excluded.figures, image_url = excluded.image_url;",
);
L.push("");

// --- projects + testimonials ---------------------------------------
const projects = site.sectors.items.flatMap((s) =>
  s.projects.map((p, i) => `  (${q(s.id)}, ${i}, ${q(p.name)}, ${q(p.location)}, ${q(p.capacity)}, ${q(p.summary)})`),
);
if (projects.length) {
  L.push("delete from public.sector_projects;");
  L.push("insert into public.sector_projects (sector_id, position, name, location, capacity, summary) values");
  L.push(projects.join(",\n") + ";");
  L.push("");
}

const quotes = site.sectors.items.flatMap((s) =>
  s.testimonials.map((t, i) => `  (${q(s.id)}, ${i}, ${q(t.quote)}, ${q(t.name)}, ${q(t.role)})`),
);
if (quotes.length) {
  L.push("delete from public.testimonials;");
  L.push("insert into public.testimonials (sector_id, position, quote, name, role) values");
  L.push(quotes.join(",\n") + ";");
  L.push("");
}

// --- product categories, sub-categories and products ---------------
// Categories are a tree: a row with parent_id set is a sub-category.
const categories = site.products.categories;
const families = categories.flatMap((c, i) => [
  { id: c.id, parent: null, position: i, label: c.label, icon: c.icon, note: c.note, specs: c.specs },
  ...c.groups.map((g, gi) => ({
    id: g.id, parent: c.id, position: gi, label: g.label,
    icon: c.icon, note: g.note, specs: [],
  })),
]);

L.push("insert into public.product_families (id, parent_id, position, label, icon, note, specs) values");
L.push(
  families
    .map((f) =>
      `  (${q(f.id)}, ${f.parent ? q(f.parent) : "null"}, ${f.position}, ${q(f.label)}, ` +
      `${q(f.icon)}, ${q(f.note)}, ${json(f.specs)})`)
    .join(",\n") +
    "\non conflict (id) do update set parent_id = excluded.parent_id," +
    " position = excluded.position, label = excluded.label, icon = excluded.icon," +
    " note = excluded.note, specs = excluded.specs;",
);
L.push("");

const products = categories.flatMap((c) => [
  ...c.products.map((p, i) => ({ family: c.id, position: i, ...p })),
  ...c.groups.flatMap((g) =>
    g.products.map((p, i) => ({ family: g.id, position: i, ...p }))),
]);

L.push("delete from public.products;");
L.push("insert into public.products (family_id, position, name, tagline, blurb, specs, image_url) values");
L.push(
  products
    .map((p) =>
      `  (${q(p.family)}, ${p.position}, ${q(p.name)}, ${q(p.tagline)}, ` +
      `${q(p.blurb)}, ${json(p.specs)}, ${q(p.image)})`)
    .join(",\n") + ";",
);
L.push("");

writeFileSync("supabase/migrations/0002_seed.sql", L.join("\n"));
console.log(
  `seed written — ${site.sectors.items.length} sectors, ${projects.length} projects, ` +
    `${quotes.length} testimonials, ${families.length} families, ${products.length} products`,
);
